server:
  port: 8081
  
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3307/blaze
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: create
        dialect: org.hibernate.dialect.MySQL5Dialect
  cache:
    type: redis
    cache-names: resource
    redis:
      time-to-live: 60000
  redis:
    host: 192.168.0.101
    port: 6379
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    use-root-path: true
    path: /api-docs/index.html
  api-docs:
    path: /api-docs
